### ISSUE TITLE
several bugs found

### ISSUE THREAD

**Issue by NewITCorp** [synw/folder_picker#1]
1. first access I got two identical lines of "Pictures" and "Pictures". shouldnt it be two dots (up one level) and "Pictures" instead?

https://uppic.cc/d/59i1

2. when root folder has no subfolder, it shows blank screen. (up one level button is missing)

thanks

**Comment by synw** [comment]
Can you provide steps to reproduce 1? 

For 2 this is a security limitation: the user is not supposed to browser upper the root folder

**Comment by synw** [comment]
No response, closing
