### ISSUE TITLE
Example throws an exception

### ISSUE THREAD

**Issue by angel1st** [synw/folder_picker#2]
Hi there, 
I found this package and I started from the example. Unfortunately, it is a bummer:
>════════ Exception Caught By widgets library ═════════════════════════
The following FileSystemException was thrown building FolderPicker(dirty, state: _FolderPickerState#8fe44):
Directory listing failed, path = '/storage/emulated/0/' (OS Error: Permission denied, errno = 13)
When the exception was thrown, this was the stack: 
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:249:5)
#2      ls (package:folder_picker/src/ls.dart:5:40)
#3      _FolderPickerState._getDirs (package:folder_picker/src/pick.dart:22:28)
#4      _FolderPickerState.build (package:folder_picker/src/pick.dart:46:15)
...
═══════════════════════════════════════════════════

It happens on both android emulator and real device. 
This is my `flutter doctor -v` output:

>[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at E:\DevTools\flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\DevTools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = E:\DevTools\Android\Sdk
    • Java binary at: E:\DevTools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

> [√] Android Studio (version 3.5)
    • Android Studio at E:\DevTools\android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

> [√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

> • No issues found!

Please let me know how to fix this.

**Comment by synw** [comment]
It was the read storage permission. That's fixed now. 

@angel1st  thanks for reporting
